[package]
name = "web-proxy"
version = "0.1.0"
authors = ["YISH"]

[dependencies]
futures = "0.1.14"
hyper = "0.11.25"
reqwest = "0.8.5"
error-chain = "0.11.0"
chrono = "0.4.2"
byteorder = "1.2.2"
toml = "0.4.6"
serde = "1.0.43"
serde_derive = "1.0.43"